### ISSUE TITLE
Runs locally but fails in Bitbucket pipeline

### ISSUE THREAD

**Issue by monicalabbao** [thebuilder/react-intersection-observer#600]
Locally, it's okay. However, when it comes to the Bitbucket Pipeline, it fails:

```
+ yarn build
yarn run v1.22.19
$ next build
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Linting and checking validity of types...

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Failed to compile.

./app/ide-editor/path/to/my/ReactComponent.tsx:23:27
Type error: Cannot find module 'react-intersection-observer' or its corresponding type declarations.
  21 | import { OtherComponent } from './OtherComponent'
  22 | import { useEffect } from 'react'
> 23 | import { useInView } from 'react-intersection-observer'
     |                           ^

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/opt/atlassian/pipelines/agent/build/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/opt/atlassian/pipelines/agent/build/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  type: 'WorkerError'
}
```

This is despite adding an `index.d.ts` as follows:

```
declare module "intersection-observer"
```

**Comment by thebuilder** [comment]
It sounds like an issue with how you have installed the package? Is it correctly saved in `package.json`?

**Comment by monicalabbao** [comment]
@thebuilder indeed, it is. The package.json is committed to the repository. Take note again, locally it works. Pipeline-wise, unfortunately no

**Comment by thebuilder** [comment]
@monicalabbao I can't really help you here. It looks like it fails as part of ESLint/TypeScripting/Jest scanning the types?
What happens if you run `tsc` to validate the types manually?

```
declare module "intersection-observer"
```

This line has nothing to do with the code failing, and I don't think you need it. You are declaring the `intersection-observer` API itself, so that is nothing something you should import directly.
